cobros/urls.py
from django.urls import path
from .views import CobrosListView

cobros_patterns = ([
    path('', CobrosListView.as_view(), name='cobros'),
    # path('<int:pk>/<slug:slug>/', , name='cobro'),
    # path('create/', , name='create'),
    # path('update/<int:pk>/', , name='update'),
    # path('delete/<int:pk>/', , name='delete'),
], 'cobros')

core/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

laurel/urls.py
from django.contrib import admin
from django.urls import path, include
from clientes.urls import clients_patterns
from cobros.urls import cobros_patterns
from prestamos.urls import prestamos_patterns

urlpatterns = [
    path('', include('core.urls')),
    path('clients/', include(clients_patterns)),
    path('cobros/', include(cobros_patterns)),
    path('prestamos/', include(prestamos_patterns)),
    path('admin/', admin.site.urls),
]

clientes/models.py
from django.db import models

# Create your models here.
class Client(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    dpi = models.CharField(max_length=30, null=True)
    nit = models.CharField(max_length=10, null=True)
    nombre = models.CharField(max_length=40, null=True)
    apellidos = models.CharField(max_length=40, null=True)
    telefonoDomicilio = models.CharField(max_length=10, null=True)
    telefonoCelular = models.CharField(max_length=10, null=True)
    telefonoReferencia = models.CharField(max_length=255, null=True)
    fechaNacimiento = models.CharField(max_length=255, null=True)
    lugarNacimiento = models.CharField(max_length=10, null=True)
    direccion = models.CharField(max_length=10, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ['apellidos', 'nombre']

    def __str__(self):
        return self.title

cobros/models.py
from django.db import models

# Create your models here.
class Cobros(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Cobro"
        verbose_name_plural = "Cobros"
        ordering = ['created']

    def __str__(self):
        return self.title

cobros/forms.py
from django import forms
from .models import Cobros

class CobrosForm(forms.ModelForm):

    class Meta:
        model = Cobros
        fields = []
        widget = {
        }

cobros/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Cobros
from .forms import CobrosForm

# Create your views here.

# Create your views here.
class CobrosListView(ListView):
    model = Cobros
    template_name = "Cobros/cobro_list.html" 

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': 'Cobros'})

class CobrosDetailView(DetailView):
    model = Cobros

class CobrosCreate(CreateView):
    model = Cobros
    form_class = CobrosForm
    success_url = reverse_lazy('Cobros:cobro')

class CobrosUpdate(UpdateView):
    model = Cobros
    fields = []
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return reverse_lazy('cobros:update', args=[self.object.id]) + '?ok'

class PageDelete(DeleteView):
    model = Cobros
    success_url = reverse_lazy('cobros:cobros')

cobros/templates/cobros/cobro_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{page.title}}{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          {{page.content|safe}}
          {% if request.user.is_staff %}
            <p><a href="{% url 'cobro:update' cobro.id %}">Editar</a></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

cobros/templates/cobros/cobro_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <br>
                <input type="submit" value="Generar Cobro" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

cobros/templates/cobros/cobro_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Clientes{% endblock %}
{% block content %}
<main role="main">
  <div class="container mb-4">
    <div style="padding-top:50px; text-align:center;">
      <h1>{{title}}</h1>
    </div>
    <h2>Listado de Clientes</h2>
    {% for cliente in client_list %}
      <span>Cliente</span>
    {% endfor %}
  </div>
</main>
{% endblock %}

cobros/templates/cobros/cobro_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          {% if 'ok' in request.GET %}
            <p style='color:green;'> modificado 
            </p>

          {% endif %}
            <form action="" method="post">{% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <br>
                <input type="submit" value="Actualizar Cobro" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}